"""empty message

Revision ID: 968395d85b29
Revises: 51b83da8ee57
Create Date: 2024-09-28 16:45:52.655773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968395d85b29'
down_revision = '51b83da8ee57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
